name: Create Azure Resources

on:
  workflow_dispatch:    

jobs:
  create-azure-resources:

    env:
      DEPLOYMENT_NAME: php-deployment
      RESOURCE_GROUP_NAME: rg-php-composer
      LOCATION: 'eastus' # You can change this to reflect the region where you deploy your ASE

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
         az group create -n ${{ env.RESOURCE_GROUP_NAME }} -l ${{ env.LOCATION }}  

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}       
          scope: resourcegroup   
          region: ${{ env.LOCATION }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}  
          deploymentName:  ${{ env.DEPLOYMENT_NAME }}
          template: ./bicep/main.bicep
          parameters: location=${{ env.LOCATION }}
                        


    